
<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Реквизиты' => 'Requisite',
    'Наименование' => 'Name',
    'Должность руководителя' => 'Doljnost_rukovoditelya',
    'ФИО полностью' => 'Fio_polnostyu',
    'Юридический адрес' => 'Official_address',
    'Наименование банка' => 'Bank_name',
    'ИНН' => 'Inn',
    'КПП' => 'Kpp',
    'ОГРН' => 'Ogrn',
    'Бик' => 'Bic',
    'КР' => 'Kr',
    'Номер расчета' => 'Nomer_rascheta',
    'тел.' => 'Tel',
    'ФИО бухгалтера' => 'Fio_buhgaltera',
    'НДС' => 'Nds',
    'Печать' => 'Pechat',
    'Организации' => 'Client',
    'email' => 'Email',
    'Договор' => 'Doc',
    'Почтовый адрес' => 'Mailing_address',
    'Код АТИ' => 'Code',
    'Водители' => 'Driver',
    'Водитель ФИО' => 'Data',
    'Данные автомобиля' => 'Data',
    'Телефон' => '',
    'Водитель паспортные данные' => 'Driver',
    'Рейсы' => 'Flight',
    'Маршрут' => 'Rout',
    'Дата' => 'Date',
    'Заказчик' => 'Zakazchik',
    'Перевозчик' => 'Carrier',
    'Дата погрузки' => 'Shipping date',
    'Адрес погрузки1' => 'Address',
    'Телефон погрузки' => 'Telephone',
    'Дата разгрузки' => 'Date',
    'Адрес разгрузки' => 'Address',
    'Телефон разгрузки' => 'Telephone',
    'Наименование груза' => 'Name',
    'вес груза' => 'Cargo weight',
    'Тип загрузки/выгрузки' => 'Type',
    'Форма оплаты' => 'Otherwise',
    'Тип оплаты' => 'Otherwise',
    'Тип оплаты' => 'Payment',
    'Кол-во дней' => 'col1',
    'Оплата Водителя' => 'Payment',
    'Форма оплаты' => 'Pay us',
    'Кол-во дней' => 'col2',
    'Оплата от Заказчика' => 'We',
    'Тип счета' => 'Fio',
    'Счёт' => 'Number',
    'Файлы' => 'File',
    'Организация Наша' => 'Organization',
    'Водитель' => 'Driver',
    'Заявка' => 'Order',
    'Вид автоперевозчика' => 'View',
    'Адрес Загрузке2' => 'Address',
    'Дата Загрузке2' => 'Date',
    'Контактное лицо и Телефон2' => 'Contact',
    'Упаковка' => 'Name',
    'Адрес Загрузке3' => 'Address',
    'Дата Загрузке3' => 'Date',
    'Контактное лицо и Телефон3' => 'Contact',
    'Наименование груза3' => 'Name',
    'Адрес Разгрузке2' => 'Address',
    'Дата  Разгрузке2' => 'Date',
    'ОбЪём М3	' => 'Volume',
    'Адрес Разгрузке3' => 'Address',
    'Дата  Разгрузке3' => 'Date',
    'Доп Информация о грузе' => 'Dop informaciya o gruze',
    'УПД' => 'Upd',
    'Дата Письмо Заказчику' => 'Date',
    'Дата Письмо от  Водителя' => 'Date',
    'Откат' => 'Recoil',
    'Ваш текст' => 'Your text',
    'Иное условие  для Заказчика' => 'Otherwise',
    'Иное условие для Водителя	' => 'Otherwise',
    'Дата заявки' => 'Date',
    'Добавить' => 'Create',
    'Вы действительно хотите удалить эту запись?' => 'Are you sure you want to delete this record?',
    'Импорт' => 'Import',
    'Удалить все' => 'Del all',
    'Справочники' => 'Reference',
    'Моя компания' => 'Company',
    'Компании' => 'Company',
    'Пользователи' => 'Users',
    'Роли' => 'Roly',
    'Отчеты' => 'Report',
    'Поля отчета' => 'Input report',
    'Шаблоны' => 'Templates',
    'М пользователи' => 'M users',
];
